# Generated by Django 5.2.4 on 2025-11-26 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('CM', 'Completed'), ('CA', 'Cancelled')], default='P', max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian tạo')),
            ],
            options={
                'verbose_name_plural': 'Lịch hẹn',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Khoa/Phòng',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên Thuốc')),
                ('unit', models.CharField(max_length=50, verbose_name='Đơn vị tính')),
                ('price', models.FloatField(verbose_name='Giá bán lẻ')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian ghi nhận')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.CharField(max_length=20, unique=True, verbose_name='Căn cước/Mã định danh')),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian tạo')),
            ],
            options={
                'verbose_name_plural': 'Người dùng',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Loại Nhân viên',
            },
        ),
        migrations.CreateModel(
            name='HealthConditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Thể loại Bệnh/Vấn đề',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bệnh viện',
            },
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Loại Kết quả',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Vai trò',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='MedicalVisit',
            fields=[
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='visit_detail', serialize=False, to='api.appointment')),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_protocol', models.TextField(blank=True, null=True, verbose_name='Phác đồ Điều trị')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian ghi nhận')),
            ],
            options={
                'verbose_name_plural': 'Chi tiết Lần khám',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_profile', serialize=False, to='api.user')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='api.department')),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.employeetype')),
            ],
            options={
                'verbose_name_plural': 'Nhân viên Bệnh viện',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_profile', serialize=False, to='api.user')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bệnh nhân',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='api.user')),
            ],
            options={
                'verbose_name_plural': 'Nhật ký hoạt động',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.role'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='invoice', serialize=False, to='api.medicalvisit')),
                ('total_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('PA', 'Paid'), ('CA', 'Cancelled')], default='P', max_length=2)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='api.patient')),
            ],
            options={
                'verbose_name_plural': 'Hóa đơn',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prescription', serialize=False, to='api.medicalvisit')),
                ('prescription_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Đơn thuốc',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file_url', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian kết thúc/Có kết quả')),
                ('result_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.resulttype')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.medicalvisit')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_results', to='api.employee')),
            ],
            options={
                'verbose_name_plural': 'Kết quả Xét nghiệm/Chẩn đoán',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'employee_type__name': 'DOCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointments', to='api.employee'),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medical_record', serialize=False, to='api.patient')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Hồ sơ Bệnh án Tổng hợp',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.patient'),
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('D', 'Drug'), ('S', 'Service')], max_length=1)),
                ('item_id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('sub_total', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.invoice')),
            ],
            options={
                'verbose_name': 'Chi tiết Hóa đơn',
                'verbose_name_plural': 'Chi tiết Hóa đơn',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dosage', models.CharField(max_length=255, verbose_name='Liều dùng')),
                ('duration_days', models.IntegerField(blank=True, null=True, verbose_name='Thời gian sử dụng (ngày)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian ghi nhận')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.drug', verbose_name='Tên Thuốc')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.prescription')),
            ],
            options={
                'verbose_name_plural': 'Chi tiết Đơn thuốc',
            },
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.medicalrecord'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_datetime')},
        ),
        migrations.CreateModel(
            name='BasicHealthcare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255, verbose_name='Tên Bệnh/Vấn đề')),
                ('detected_year', models.IntegerField(blank=True, null=True, verbose_name='Năm phát hiện')),
                ('current_status', models.CharField(default='Đang theo dõi', max_length=100, verbose_name='Tình trạng')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian ghi nhận')),
                ('condition_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.healthconditiontype', verbose_name='Thể loại')),
                ('detected_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hospital', verbose_name='Phát hiện tại BV')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_conditions', to='api.medicalrecord')),
            ],
            options={
                'verbose_name_plural': 'Thông tin Sức khỏe Cơ bản (Bệnh sử)',
                'unique_together': {('medical_record', 'disease_name', 'condition_type')},
            },
        ),
    ]
