# Generated by Django 5.2.4 on 2025-11-22 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('D', 'Drug'), ('S', 'Service')], max_length=1)),
                ('item_id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('sub_total', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.invoice')),
            ],
            options={
                'verbose_name': 'Chi tiết Hóa đơn',
                'verbose_name_plural': 'Chi tiết Hóa đơn',
            },
        ),
    ]
