# Generated by Django 5.2.4 on 2025-11-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('IP', 'In Progress'), ('CM', 'Completed'), ('CA', 'Cancelled')], default='P', max_length=2),
        ),
    ]
